repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
      - id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        exclude: .venv([23])?|migrations|node_modules|.flake8|.isort.cfg|.pre-commit-config.yaml|README.md|Dockerfile|settings.py|nginx-proxy-dev.conf|nginx-proxy-prod.conf
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.9
        entry: black --config pyproject.toml --fast src/
        exclude: .venv([23])?|migrations|node_modules|.flake8|.isort.cfg|.pre-commit-config.yaml|README.md
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        entry: bandit -c .bandit.yaml
        exclude: ^src/api/tests/
