version: '3.9'

services:
  api:  &api
    user: "container_user:container_user"
    container_name: rapi_buy_api
    image: rapi_buy/api:latest
    command: manage runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./src:/opt/backend/
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - cache
    links:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.3
    restart: unless-stopped
    container_name: b2b_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./utils/sql:/docker-entrypoint-initdb.d
    environment:
      - DEBUG=TRUE
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=rapi_buy

  nginx:
    image: nginx:1.21.1
    container_name: rapi_buy-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/concatenated.cer:/etc/ssl/concatenated.cer
      - ./ssl/private_key.key:/etc/ssl/private_key.key
      - ./src/static:/opt/backend/static
    depends_on:
      - api

volumes:
  pgdata:
