# Generated by Django 3.2 on 2021-07-31 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("delivery", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shippings",
                to="store.order",
            ),
        ),
        migrations.AddField(
            model_name="shipping",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shippings",
                to="delivery.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="deliveryman",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="account.account",
            ),
        ),
    ]
