# Generated by Django 3.2.10 on 2022-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Apellidos'),
        ),
    ]
